import { MAX_GUARDIANS } from '@/lib/constants';

// ---------------------------------------------------------------------------
// CRC16-CCITT (XModem variant) used by Stellar StrKey encoding
// ---------------------------------------------------------------------------

/**
 * Compute CRC16-CCITT (XModem) over `data`.
 * Polynomial: 0x1021, init: 0x0000, no reflection.
 */
function crc16(data: Uint8Array): number {
  let crc = 0x0000;
  for (let i = 0; i < data.length; i++) {
    crc ^= data[i] << 8;
    for (let j = 0; j < 8; j++) {
      if (crc & 0x8000) {
        crc = (crc << 1) ^ 0x1021;
      } else {
        crc <<= 1;
      }
      crc &= 0xffff;
    }
  }
  return crc;
}

// RFC 4648 base32 alphabet (used by Stellar StrKey)
const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

/**
 * Decode a base32 string (Stellar/RFC 4648 alphabet, no padding) into bytes.
 * Returns null if the input contains characters outside the alphabet.
 */
function decodeBase32(input: string): Uint8Array | null {
  const bytes: number[] = [];
  let buffer = 0;
  let bitsLeft = 0;

  for (let i = 0; i < input.length; i++) {
    const val = BASE32_ALPHABET.indexOf(input[i]);
    if (val === -1) return null;
    buffer = (buffer << 5) | val;
    bitsLeft += 5;
    if (bitsLeft >= 8) {
      bitsLeft -= 8;
      bytes.push((buffer >> bitsLeft) & 0xff);
    }
  }

  return new Uint8Array(bytes);
}

/**
 * Verify that `address` is a valid Stellar StrKey account address.
 *
 * A Stellar account address encodes (via base32):
 *   - 1 version byte (0x06 << 3 = 0x30 for account keys, which encodes as 'G')
 *   - 32 payload bytes (the ed25519 public key)
 *   - 2 checksum bytes (CRC16-CCITT over the preceding 33 bytes, little-endian)
 *
 * Total raw bytes: 35 → ceil(35 * 8 / 5) = 56 base32 characters.
 */
function verifyStellarStrKey(address: string): boolean {
  const raw = decodeBase32(address);
  if (!raw || raw.length !== 35) return false;

  // The last 2 bytes are the CRC16 checksum (little-endian).
  const payload = raw.slice(0, 33);
  const expectedCrc = raw[33] | (raw[34] << 8);
  const actualCrc = crc16(payload);

  return actualCrc === expectedCrc;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns true when `address` is a syntactically valid Stellar account address
 * AND its embedded CRC16 checksum is correct.
 *
 * Note: existing test fixtures use repeated-character addresses (e.g. 56× 'A')
 * that are format-valid but have incorrect checksums. Those will correctly
 * return false from this function — do not use them as "valid" test fixtures.
 * Use a real Stellar address (or one generated by `stellar-sdk`) instead.
 */
export function isValidStellarAddress(address: string): boolean {
  if (!/^G[A-Z2-7]{55}$/.test(address)) return false;
  return verifyStellarStrKey(address);
}

export interface GuardianValidationResult {
  rowErrors: string[];
  topError: string | null;
}

export function validateGuardians(
  guardians: string[],
  ownerAddress: string | null,
): GuardianValidationResult {
  const rowErrors: string[] = guardians.map(() => '');
  let topError: string | null = null;

  const seen = new Set<string>();
  let validCount = 0;

  for (let i = 0; i < guardians.length; i++) {
    const g = guardians[i].trim();
    if (g === '') continue;

    if (!isValidStellarAddress(g)) {
      rowErrors[i] = 'Not a valid Stellar address (must start with G and be 56 characters)';
      continue;
    }

    if (ownerAddress && g === ownerAddress) {
      rowErrors[i] = 'A guardian cannot be the same as the will owner';
      continue;
    }

    if (seen.has(g)) {
      rowErrors[i] = 'Duplicate guardian address';
      continue;
    }

    seen.add(g);
    validCount++;
  }

  // #238: enforce the contract's guardian limit
  if (validCount > MAX_GUARDIANS) {
    topError = `You can add at most ${MAX_GUARDIANS} guardians.`;
    return { rowErrors, topError };
  }

  const hasRowErrors = rowErrors.some((e, i) => e !== '' && guardians[i].trim() !== '');
  if (hasRowErrors) {
    topError = 'Please fix the guardian address errors above before continuing.';
  }

  return { rowErrors, topError };
}
