import { describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ToastProvider } from '@/components/Toast';
import DashboardPage from '@/app/dashboard/page';
vi.mock('@/lib/freighter', () => ({ safeGetPublicKey: vi.fn().mockResolvedValue(null) }));
vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn() }), useSearchParams: () => new URLSearchParams() }));
const { will } = vi.hoisted(() => ({ will: { id: '42', owner: 'GDBRZV77PZDK7LRBXEUPZNGJNQLFQKAZD6PKS7JFAZAKU4H3FDON4JL4', token: 'C'.padEnd(56, 'A'), balance: '0', beneficiaries: [{ address: 'GDSWYNUBEHPVKWC3Q5CYRG6QZIMGR5P5ZRYSRZBCRN2VHQY7Z67HFCEF', percentage: 100 }], guardians: [], guardianVotes: 0, status: 'Active', lastCheckin: new Date(), checkinPeriodDays: 90, gracePeriodDays: 7, triggerTime: null } }));
vi.mock('@/lib/sorowill', () => ({ getSoroWillClient: () => ({ getWillsByOwner: vi.fn().mockResolvedValue([will]), getWillsByBeneficiary: vi.fn().mockResolvedValue([]) }), getWillsByGuardian: vi.fn().mockResolvedValue({ wills: [], hasErrors: false }) }));
describe('dashboard page', () => { it('renders empty state with mocked client', async () => { render(<ToastProvider><DashboardPage /></ToastProvider>); expect(await screen.findByText(/no wills/i)).toBeInTheDocument(); }); it('switches tabs and applies search/filter controls', async () => { const user = userEvent.setup(); render(<ToastProvider><DashboardPage /></ToastProvider>); await user.click(await screen.findByRole('tab', { name: /inheriting/i })); expect(screen.getByRole('tab', { name: /inheriting/i })).toHaveAttribute('aria-selected', 'true'); const search = screen.getByPlaceholderText(/search by will/i); await user.type(search, 'missing'); expect(await screen.findByText(/no matching wills|no wills match/i)).toBeInTheDocument(); }); });
